### ISSUE TITLE
KeyError: 'DmozItem' using Scrapy (1.1.0), rethinkdb (2.3.0.post3)

### ISSUE THREAD

**Issue by kudotty** [ownport/scrapy-rethinkdb#4]
```
$ scrapy crawl dmoz
2016-05-26 20:41:18 [scrapy] INFO: Scrapy 1.1.0 started (bot: scrapy_tutorial)
2016-05-26 20:41:18 [scrapy] INFO: Overridden settings: {'BOT_NAME': 'scrapy_tutorial', 'NEWSPIDER_MODULE': 'scrapy_tutorial.spiders', 'SPIDER_MODULES': ['scrapy_tutorial.spiders'], 'ROBOTSTXT_OBEY': True}
2016-05-26 20:41:18 [scrapy] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats', 'scrapy.extensions.logstats.LogStats']
2016-05-26 20:41:18 [scrapy] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.chunked.ChunkedTransferMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2016-05-26 20:41:18 [scrapy] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2016-05-26 20:41:18 [scrapy] INFO: Enabled item pipelines:
['scrapy_rethinkdb.RethinkDBPipeline']
2016-05-26 20:41:18 [scrapy] INFO: Spider opened
2016-05-26 20:41:18 [scrapy] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2016-05-26 20:41:18 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/robots.txt> (referer: None)
2016-05-26 20:41:19 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/> (referer: None)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Resources/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Conferences/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Web/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Mailing_Lists/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Commercial_Services/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/User_Groups/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] DEBUG: Crawled (200) <GET http://www.dmoz.org/Computers/Programming/Languages/Python/Personal_Pages/> (referer: http://www.dmoz.org/Computers/Programming/Languages/Python/)
2016-05-26 20:41:20 [scrapy] ERROR: Error processing {'desc': ['\r\n\r\n                    '], 'link': ['/'], 'title': ['Top']}
Traceback (most recent call last):
  File "/Users/me/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/me/.anyenv/envs/pyenv/versions/3.5.1/lib/python3.5/site-packages/scrapy_rethinkdb/pipeline.py", line 75, in process_item
    insert_stmt = self.table_mapping[item.__class__.__name__].insert(document, **self.insert_options)
KeyError: 'DmozItem'

...(repeat)

2016-05-26 20:41:47 [scrapy] INFO: Closing spider (finished)
2016-05-26 20:41:47 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 5491,
 'downloader/request_count': 15,
 'downloader/request_method_count/GET': 15,
 'downloader/response_bytes': 100641,
 'downloader/response_count': 15,
 'downloader/response_status_count/200': 15,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2016, 5, 26, 11, 41, 47, 578203),
 'log_count/DEBUG': 15,
 'log_count/ERROR': 249,
 'log_count/INFO': 7,
 'request_depth_max': 1,
 'response_received_count': 15,
 'scheduler/dequeued': 14,
 'scheduler/dequeued/memory': 14,
 'scheduler/enqueued': 14,
 'scheduler/enqueued/memory': 14,
 'start_time': datetime.datetime(2016, 5, 26, 11, 41, 44, 696171)}
2016-05-26 20:41:47 [scrapy] INFO: Spider closed (finished)
```

**Comment by kudotty** [comment]
please, help me.

**Comment by ownport** [comment]
Could you please share with me your code because the python 3.5 is supported https://travis-ci.org/ownport/scrapy-rethinkdb/builds/132668241
- could you please check that you pass to pipeline the object as DmozItem and not as dictionary

**Comment by kudotty** [comment]
exact copy of scrapy tutorial + scrapy_rethinkdb.RethinkDBPipeline
https://github.com/kudotty/scrapy-tutorial-rethinkdb

**Comment by kudotty** [comment]
I got the same KeyError using Python 2.7.11

**Comment by ownport** [comment]
The repository https://github.com/kudotty/scrapy-tutorial-rethinkdb is not available

**Comment by ownport** [comment]
Please share your configuration with parameter

RETHINKDB_TABLE_MAPPING = {
    'Item': 'items',
}

in this map, the key is class name of your item, the value is RethinkDB table name

**Comment by kudotty** [comment]
https://github.com/kudotty/scrapy-tutorial-rethinkdb/blob/master/scrapy_tutorial/settings.py#L67-L72

**Comment by kudotty** [comment]
Please re-chek my repo.

**Comment by kudotty** [comment]
Sorry. Fixed my mistake
https://github.com/kudotty/scrapy-tutorial-rethinkdb/commit/a2aab2e7f29e5e878628efa805205564b1f2c439

**Comment by ownport** [comment]
You need to use DmozItem instead of Item in settings.py 

``` python
RETHINKDB_TABLE_MAPPING = {
'DmozItem': 'items',
}
```

**Comment by kudotty** [comment]
Oh, I see!.
Thank you very much.

**Comment by ownport** [comment]
May I close the issue?
